### ISSUE TITLE
Project Definition

### ISSUE THREAD

**Issue by Moamin-AbuEwaida** [bringmetheaxx/TeamFour#12]
We all need to brainstorm together to touchdown on the headlines and big image of the project and the out come from it
then come up with the idea to start the next step of project backlog

**Comment by danielhalasz** [comment]
[Project definition](https://github.com/HackYourFutureBelgium/incremental-development/blob/master/planning-and-collaborating/3-project-definition.md) is to be filled by @lauraramirez220612 and @Senait-coding in in this file: 
https://github.com/bringmetheaxx/TeamFour/blob/main/README.md
